org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

# platform
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.235
neo_version_range=[21.1.235,)
loader_version_range=[4,)

# mod
mod_id=morewheels
mod_name=Create: More Wheels
mod_license=MIT
mod_version=0.1.0
mod_group_id=dev.danzy.morewheels
mod_authors=Danzy
mod_description=Extra wheels and tires for Create: Aeronautics (Offroad).
